require: rubocop-rspec

AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - vendor/*
    - bin/*
    - Guardfile
  RunRailsCops: true

# CoffeeScript:
#   Enabled: true

# Ruby:
#   Enabled: true

# Rails

Rails/ActionFilter:
  Enabled: true

Rails/Delegate:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: false

# Style

Style/AccessorMethodName:
  Enabled: true

Style/Alias:
  Enabled: true

Style/AlignHash:
  Enabled: false

Style/AlignParameters:
  Enabled: true
  EnforcedStyle: with_fixed_indentation

Style/ArrayJoin:
  Enabled: true

Style/AsciiComments:
  Enabled: true

Style/AsciiIdentifiers:
  Enabled: true

Style/Attr:
  Enabled: true

Metrics/BlockNesting:
  Enabled: true

Style/CaseEquality:
  Enabled: true

Style/CharacterLiteral:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: true

Metrics/ClassLength:
  Enabled: true

Style/ClassVars:
  Enabled: true

Style/CollectionMethods:
  Enabled: false

Style/ColonMethodCall:
  Enabled: true

Style/CommentAnnotation:
  Enabled: true

Metrics/CyclomaticComplexity:
  Enabled: true

Style/DeprecatedHashMethods:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: leading

Style/DoubleNegation:
  Enabled: true

Style/EachWithObject:
  Enabled: true

Style/EmptyLiteral:
  Enabled: true

Style/EvenOdd:
  Enabled: true

Style/FileName:
  Enabled: false

Style/FlipFlop:
  Enabled: true

Style/FormatString:
  Enabled: true
  EnforcedStyle: percent

Style/GlobalVars:
  Enabled: true

Style/GuardClause:
  Enabled: true

Style/IfUnlessModifier:
  Enabled: false

Style/IfWithSemicolon:
  Enabled: true

Style/Lambda:
  Enabled: true

Style/LambdaCall:
  Enabled: true

Style/LineEndConcatenation:
  Enabled: true

Metrics/LineLength:
  Max: 100
  Exclude:
  - db/seeds.rb

Metrics/MethodLength:
  Enabled: true

Style/MethodDefParentheses:
  Enabled: false

Style/DefWithParentheses:
  Enabled: true

Style/ModuleFunction:
  Enabled: true

Style/NegatedIf:
  Enabled: true

Style/NegatedWhile:
  Enabled: true

Style/Next:
  Enabled: true

Style/NilComparison:
  Enabled: true

Style/Not:
  Enabled: true

Style/NumericLiterals:
  Enabled: true

Style/OneLineConditional:
  Enabled: false

Style/OpMethod:
  Enabled: true

Metrics/ParameterLists:
  Enabled: true

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%': '{}'

Style/PerlBackrefs:
  Enabled: true

Style/PredicateName:
  NamePrefixBlacklist:
    - is_

Style/Proc:
  Enabled: true

Style/RaiseArgs:
  Enabled: true

Style/RegexpLiteral:
  Enabled: true

Style/SelfAssignment:
  Enabled: true

Style/SingleLineBlockParams:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/SignalException:
  Enabled: true

Style/SpaceBeforeBlockBraces:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: true

Style/StringLiterals:
  Enabled: false

Style/VariableInterpolation:
  Enabled: true

Style/TrailingComma:
  Enabled: false

Style/TrivialAccessors:
  Enabled: true

Style/VariableInterpolation:
  Enabled: true

Style/WhenThen:
  Enabled: true

Style/WhileUntilModifier:
  Enabled: false

Style/WordArray:
  Enabled: true

# Lint

Lint/AmbiguousOperator:
  Enabled: true

Lint/AmbiguousRegexpLiteral:
  Enabled: true

Lint/AssignmentInCondition:
  Enabled: true

Lint/ConditionPosition:
  Enabled: true

Lint/DeprecatedClassMethods:
  Enabled: true

Lint/ElseLayout:
  Enabled: true

Lint/HandleExceptions:
  Enabled: true

Lint/InvalidCharacterLiteral:
  Enabled: false

Lint/LiteralInCondition:
  Enabled: true

Lint/LiteralInInterpolation:
  Enabled: true

Lint/Loop:
  Enabled: true

Lint/ParenthesesAsGroupedExpression:
  Enabled: true

Lint/RequireParentheses:
  Enabled: true

Lint/UnderscorePrefixedVariableName:
  Enabled: true

Lint/Void:
  Enabled: true