sudo: false
language: ruby
rvm:
  - 2.3.0
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database campaigns_test;' -U postgres
  - bundle exec rake db:migrate --trace
addons:
  code_climate:
    repo_token: 481129ba6a90c2196ec04b071f662f9af0014d78135d92626ea8f3a387d11e9a
deploy:
  provider: heroku
  api_key:
    secure: NAa43T12yLwZneO30Lf+R4cH3IIYJVSjpYyMM1dO1Iibtk5CYmlXs56E+DhNhDwr9V7xwsMTwRtU//SmiaFGt4My4Ttb58o7T2rL3reoqazbsCBPto+qAqPW8SUm8n58DFPQ3uzpUPPwZkDMx8JyurKNoCokAvlaigyRZnV/puM=
  app: rpgcampaigns
  on:
    repo: fantasygame/campaigns
  run: "rake db:migrate"
