# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 7d134ad3e1ecd483116e68359cd9ca167dc078427e4f3112149fb4897580714a31c10c047b9d600879a13fc7c1fd7ac5352d5169a08aed1c9aab49a6eabeed89
  email_provider_username: <%= ENV["DEV_EMAIL_PROVIDER_USERNAME"] %>
  email_provider_password: <%= ENV["DEV_EMAIL_PROVIDER_PASSWORD"] %>
  email_provider_address: <%= ENV["DEV_EMAIL_PROVIDER_ADDRESS"] %>
test:
  domain_name: example.com 
  secret_key_base: 65d73278cfd0163fbe5375b04d65c07c06a130932d273d7a37990821fae82df2982299cfa03d267ec50b925e55f1f1ea5176a6f6a6d7d9500a87fa9439a658a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  email_provider_username: <%= ENV["EMAIL_PROVIDER_USERNAME"] %>
  email_provider_password: <%= ENV["EMAIL_PROVIDER_PASSWORD"] %>
  email_provider_address: <%= ENV["EMAIL_PROVIDER_ADDRESS"] %>
